### ISSUE TITLE
err BSON

### ISSUE THREAD

**Issue by kaflan** [scotch-io/easy-node-authentication#30]
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
The magic happens on port 8080
events.js:141

**Comment by kaflan** [comment]
bad read documentation

**Comment by kaflan** [comment]
close

**Comment by abebraham** [comment]
wait, how did you fix it?

**Comment by iamromuald** [comment]
@abebraham updating your mongoose dependancy to the latest version should do the trick 😉
