### ISSUE TITLE
Google Authentication Not Working

### ISSUE THREAD

**Issue by msfragala** [scotch-io/easy-node-authentication#49]
Google authentication is hitting an error on the callback URL:

```
Error
   at /Users/Mitchell/Repository/easy-node-authentication/node_modules/passport-google-oauth20/lib/strategy.js:95:21
   at passBackControl (/Users/Mitchell/Repository/easy-node-authentication/node_modules/oauth/lib/oauth2.js:132:9)
   at IncomingMessage.<anonymous> (/Users/Mitchell/Repository/easy-node-authentication/node_modules/oauth/lib/oauth2.js:157:7)
   at emitNone (events.js:110:20)
   at IncomingMessage.emit (events.js:207:7)
   at endReadableNT (_stream_readable.js:1045:12)
   at _combinedTickCallback (internal/process/next_tick.js:138:11)
   at process._tickCallback (internal/process/next_tick.js:180:9)
```

For clarification, the only changes I made were swapping in my credentials from the Google Developers Console and the URL for my local mongodb server.

**Comment by obrienstat** [comment]
you might need to add google+ api to your project. In your google developers page, go to your dashboard, and click on enable api, then look for google+ api and select it, this will enable it.

**Comment by obrienstat** [comment]
If you are still having issues feel free to check out my repositories under nwen304-group-project > config > passport.js
This is a fairly recent implementation of oauth and how I set it up for my site. You are welcome to use it

**Comment by msfragala** [comment]
@obrienstat Yes, that did it — thank you! Not sure if that was mentioned somewhere and missed it.

**Comment by svantetobias** [comment]
> you might need to add google+ api to your project. In your google developers page, go to your dashboard, and click on enable api, then look for google+ api and select it, this will enable it.

Non-obvious solution! Creating the credentials in Google API is not enough - you also have to enable the Google+ API after creating the credentials.
