### ISSUE TITLE
Facebook name returns 'undefined undefined'

### ISSUE THREAD

**Issue by libnine** [scotch-io/easy-node-authentication#53]
In passport.js:

    // facebook
    passport.use(new FacebookStrategy({
        clientID: configAuth.facebookAuth.clientID,
        clientSecret: configAuth.facebookAuth.clientSecret,
        callbackURL: configAuth.facebookAuth.callbackURL,
        passReqToCallback : true
    },
    function(req, token, refreshToken, profile, done) {
        process.nextTick(function() {
            if (!req.user) {
                User.findOne({ 'facebook.id' : profile.id }, function(err, user) {
                    if (err)
                        return done(err);
                    if (user) {
                        if (!user.facebook.token) {
                            user.facebook.token = token;
                            user.facebook.name  = profile.name.givenName + ' ' + profile.name.familyName;
                            user.facebook.email = profile.email;

                            user.save(function(err) {
                                if (err)
                                    throw err;
                                return done(null, user);
                            });
                        }

                        return done(null, user); // user found, return that user
                    } else {
                        var newUser            = new User();

                        newUser.facebook.id    = profile.id;
                        newUser.facebook.token = token;
                        newUser.facebook.name  = profile.name.givenName + ' ' + profile.name.familyName;
                        newUser.facebook.email = profile.email;

                        newUser.save(function(err) {
                            if (err)
                                throw err;
                            return done(null, newUser);
                        });
                    }
                });

            } else {
                var user            = req.user;

                user.facebook.id    = profile.id;
                user.facebook.token = token;
                user.facebook.name  = profile.name.givenName + ' ' + profile.name.familyName;
                user.facebook.email = profile.email;

                user.save(function(err) {
                    if (err)
                        throw err;
                    return done(null, user);
                });
            }
        });
    }));

in routes.js:

  app.get('/auth/facebook', passport.authenticate('facebook', { scope : 'email' }));

  app.get('/auth/facebook/callback',
      passport.authenticate('facebook', {
          successRedirect : '/profile',
          failureRedirect : '/'
  }));

I've spent a couple hours trying to figure out why 'newUser.facebook.name  = profile.name.givenName + ' ' + profile.name.familyName;' keeps returning 'undefined undefined' - any ideas?

**Comment by fatima-alansari** [comment]
@libnine #53 I had the same issue. The issue is two fold: one it's been a few years and the FB API has changes that affect this code. And two, there is a small issue with the model, probably caused by issue no.1.

1. In auth.js, below FB's "callbackURL", add:
```
module.exports = {

  /* Facebook Authorization */
  'facebookAuth': {
    'clientID': 'yourclientid',
    'clientSecret': 'yourclientsecret',
    'callbackURL': 'http://localhost:3000/auth/facebook/callback', // Change URL to your app
    'profileFields': ['id', 'email', 'name'] // Add permissions as needed. Check FB API docs for what permissions are available
  }
};
```

2. In passport.js, fix the new FacebookStrategy:
```
passport.use(new FacebookStrategy({
    clientID: configAuth.facebookAuth.clientID,
    clientSecret: configAuth.facebookAuth.clientSecret,
    callbackURL: configAuth.facebookAuth.callbackURL,
    profileFields: configAuth.facebookAuth.profileFields,
    enableProof: true, // For security
    passReqToCallback: true // Pass request from route
  },
```

3. In user.js schema, make sure the _order_ of your fields is correct:
```
const UserSchema = mongoose.Schema({
  local: {
    email: String,
    password: String
  },
  facebook: {
    id: String,
    token: String,
    name: String,
    email: String
  }
};
```

Yeah, the fact that the tutorial has email above name in the schema _broke_ the code! Hopefully, this will be enough to fix your issues and anyone else's :) I'm not sure if I should do a pull request for this? It doesn't seem to be updated anymore.

**Comment by sevilayha** [comment]
Thanks for the insight. A pull request would be great. I'm planning on doing a big update of this and a PR would be a big help.

**Comment by fatima-alansari** [comment]
@sevilayha I am at work right now, I will get to it later today!
